-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 01, 2023 at 08:55 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `chatbot`
--

-- --------------------------------------------------------

--
-- Table structure for table `chat`
--

CREATE TABLE `chat` (
  `id` int(11) NOT NULL,
  `pertanyaan` text NOT NULL,
  `jawaban` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `chat`
--

INSERT INTO `chat` (`id`, `pertanyaan`, `jawaban`) VALUES
(11, 'Resep nasi uduk / cara membuat nasi uduk / Bagaimana cara membuat nasi uduk?', 'Nasi uduk Betawi adalah nasi yang dimasak dengan santan dan rempah-rempah khas. Biasanya disajikan dengan lauk-pauk seperti ayam goreng, telur dadar, dan emping.\n<br>\n<br>\nBahan-bahan:\n<br>\n•	2 gelas beras\n<br>\n•	400 ml santan kental\n<br>\n•	2 lembar daun salam\n<br>\n•	2 batang serai, memarkan\n<br>\n•	2 cm lengkuas, memarkan\n<br>\n•	1 sdt garam\n<br>\n•	1/2 sdt kaldu bubuk\n<br>\n•	Air secukupnya\n<br>\n<br>\nBahan pelengkap:\n<br>\n•	Ayam goreng\n<br>\n•	Telur dadar\n<br>\n•	Emping goreng\n<br>\n•	Bawang merah goreng\n<br>\n•	Irisan mentimun\n<br>\n<br>\nCara membuat:\n<br>\n•	Cuci bersih beras, kemudian tiriskan.\n<br>\n•	Siapkan panci atau rice cooker, masukkan beras ke dalamnya.\n<br>\n•	Tambahkan santan, daun salam, serai, dan lengkuas ke dalam panci atau rice cooker.\n<br>\n•	Tuang air secukupnya hingga mencukupi level air untuk memasak nasi.\n<br>\n•	Tambahkan garam dan kaldu bubuk, aduk rata.\n<br>\n•	Masak nasi seperti biasa, baik dengan menggunakan panci atau rice cooker hingga matang sempurna.\n<br>\n•	Setelah nasi matang, biarkan sejenak hingga uap panasnya hilang.\n<br>\n•	Angkat daun salam, serai, dan lengkuas dari nasi.\n<br>\n•	Nasi uduk Betawi siap disajikan.\n<br>\n•	Sajikan nasi uduk dengan ayam goreng, telur dadar, emping goreng, bawang merah goreng, dan irisan mentimun sebagai pelengkap.\n'),
(12, 'Resep Soto Betawi/ cara membuat Soto Betawi / Bagaimana cara membuat Soto Betawi?', 'Soto Betawi adalah sup daging sapi dengan kuah santan yang kaya rempah. Di dalamnya terdapat potongan daging sapi, kentang, dan tomat. Soto Betawi biasanya disajikan dengan nasi dan kerupuk.\r\n<br>\r\n<br>\r\nBahan-bahan:\r\n<br>\r\n•	500 gram daging sapi, potong-potong\r\n<br>\r\n•	1 liter air\r\n<br>\r\n•	400 ml santan kental\r\n<br>\r\n•	2 lembar daun jeruk purut\r\n<br>\r\n•	2 batang serai, memarkan\r\n<br>\r\n•	2 cm lengkuas, memarkan\r\n<br>\r\n•	3 lembar daun salam\r\n<br>\r\n•	3 lembar daun bawang, iris halus\r\n<br>\r\n•	2 batang seledri, iris halus\r\n<br>\r\n•	2 sdm minyak goreng\r\n<br>\r\n•	Bawang merah goreng untuk taburan\r\n<br>\r\n•	Garam secukupnya\r\n<br>\r\n•	Merica secukupnya\r\n<br>\r\n<br>\r\nBumbu Halus:\r\n<br>\r\n•	6 butir bawang merah\r\n<br>\r\n•	4 siung bawang putih\r\n<br>\r\n•	2 cm jahe\r\n<br>\r\n•	2 cm kunyit\r\n<br>\r\n•	2 butir kemiri\r\n<br>\r\n•	1 sdt ketumbar\r\n<br>\r\n•	1/2 sdt jintan\r\n<br>\r\n•	3 butir kemiri\r\n<br>\r\n<br>\r\nBahan Pelengkap:\r\n<br>\r\n•	Soun, seduh air panas dan tiriskan\r\n<br>\r\n•	Kentang goreng, potong dadu dan goreng hingga matang\r\n<br>\r\n•	Telur rebus, belah dua\r\n<br>\r\n•	Cara membuatnya:\r\nPanaskan minyak goreng dalam panci, tumis bumbu halus hingga harum.\r\n<br>\r\n•	Masukkan daging sapi, aduk hingga berubah warna.\r\n<br>\r\n•	Tambahkan air, daun jeruk purut, serai, lengkuas, dan daun salam. Masak hingga daging empuk.\r\n<br>\r\n•	Setelah daging empuk, tambahkan santan, garam, dan merica. Aduk rata dan masak sebentar hingga mendidih.\r\n<br>\r\n•	Masukkan daun bawang dan seledri, aduk sebentar.\r\n<br>\r\n•	Soto Betawi siap disajikan dalam mangkuk, taburi dengan bawang merah goreng.\r\n<br>\r\n•	Sajikan Soto Betawi dengan soun, kentang goreng, dan telur rebus sebagai pelengkap.\r\n'),
(13, 'Resep Ketoprak / cara membuat Ketoprak / Bagaimana cara membuat Ketoprak?', 'Ketoprak Betawi adalah campuran tahu, bihun, lontong, sayuran segar, dan kerupuk yang disiram dengan bumbu kacang. Rasanya gurih dan sedikit pedas.\r\n<br>\r\n<br>\r\nBahan bahan:\r\n<br>\r\n•	200 gram tahu putih, potong-potong\r\n<br>\r\n•	200 gram lontong, potong-potong\r\n<br>\r\n•	100 gram bihun, rendam dalam air panas dan tiriskan\r\n<br>\r\n•	100 gram tauge, seduh dengan air panas dan tiriskan\r\n<br>\r\n•	2 buah mentimun, iris tipis\r\n<br>\r\n•	2 batang daun selada, iris kasar\r\n<br>\r\n•	2 sdm bawang merah goreng\r\n<br>\r\n•	2 sdm kacang tanah goreng\r\n<br>\r\n•	2 sdm ebi (udang kering), sangrai\r\n<br>\r\n\r\n•	Minyak goreng secukupnya\r\n<br>\r\n<br>\r\nBumbu Kacang:\r\n<br>\r\n•	100 gram kacang tanah, sangrai\r\n<br>\r\n•	3 siung bawang putih\r\n<br>\r\n•	5 buah cabe rawit merah\r\n<br>\r\n•	2 sdm gula merah, serut\r\n<br>\r\n•	1 sdt terasi bakar\r\n<br>\r\n•	1/2 sdt garam\r\n<br>\r\n•	200 ml air matang\r\n<br>\r\n<br>\r\nCara membuat:\r\n<br>\r\n•	Haluskan bumbu kacang menggunakan blender atau ulekan. Tambahkan air sedikit demi sedikit hingga membentuk pasta kental. Sisihkan.\r\n<br>\r\n•	Panaskan minyak dalam wajan, goreng tahu hingga kecokelatan. Angkat dan tiriskan.\r\n<br>\r\n•	Rebus lontong dalam air mendidih hingga matang, angkat dan tiriskan.\r\n<br>\r\n•	Siapkan piring saji, susun lontong, tahu, bihun, tauge, mentimun, dan daun selada.\r\n<br>\r\n•	Siram Ketoprak dengan bumbu kacang yang telah dibuat.\r\n<br>\r\n•	Taburi Ketoprak dengan bawang merah goreng, kacang tanah goreng, dan ebi sangrai.\r\n<br>\r\n•	Ketoprak Betawi siap disajikan.\r\n'),
(14, 'Resep kerak telor / cara membuat kerak telor / Bagaimana cara membuat kerak telor?', 'Kerak telor adalah makanan khas Betawi yang terbuat dari beras ketan, telur ayam, serundeng, dan bawang goreng. Rasanya gurih dan legit.\r\n<br>\r\n<br>\r\nBahan-Bahan:\r\n<br>\r\n•	200 gram beras ketan putih\r\n<br>\r\n•	4 butir telur ayam\r\n<br>\r\n•	50 gram ebi (udang kering), sangrai dan haluskan\r\n<br>\r\n•	2 batang daun bawang, iris halus\r\n<br>\r\n•	2 sdm kelapa parut sangrai\r\n<br>\r\n•	2 sdm bawang merah goreng\r\n<br>\r\n•	Minyak goreng secukupnya\r\n<br>\r\n<br>\r\nBumbu Halus:\r\n<br>\r\n•	6 butir bawang merah\r\n<br>\r\n•	3 siung bawang putih\r\n<br>\r\n•	2 butir kemiri\r\n<br>\r\n•	2 cm kencur\r\n<br>\r\n•	1 cm jahe\r\n<br>\r\n•	1 cm kunyit\r\n<br>\r\n•	1 sdt terasi bakar\r\n<br>\r\n•	1 sdt garam\r\n<br>\r\n<br>\r\nCara Membuat:\r\n<br>\r\n•	Rendam beras ketan dalam air selama minimal 4 jam, kemudian tiriskan.\r\n<br>\r\n•	Haluskan bumbu halus menggunakan blender atau ulekan.\r\n<br>\r\n•	Panaskan minyak goreng dalam wajan, tumis bumbu halus hingga harum.\r\n<br>\r\n•	Tambahkan ebi (udang kering) yang telah disangrai dan haluskan, aduk rata.\r\n<br>\r\n•	Masukkan beras ketan, aduk hingga rata dengan bumbu. Masak dengan api kecil hingga ketan matang dan lengket.\r\n<br>\r\n•	Pecahkan telur ayam ke dalam wadah, kocok lepas.\r\n<br>\r\n•	Panaskan minyak dalam wajan datar, tuang setengah bagian telur ke wajan, ratakan.\r\n<br>\r\n•	Tambahkan setengah bagian adonan ketan di atas telur, ratakan dan tekan-tekan hingga padat.\r\n<br>\r\n•	Balik telur dengan adonan ketan, masak hingga kedua sisi berwarna kecokelatan.\r\n<br>\r\n•	Angkat Kerak Telor dari wajan, taburi dengan kelapa parut sangrai dan bawang merah goreng.\r\n<br>\r\n•	Potong-potong Kerak Telor dan sajikan selagi hangat.\r\n'),
(15, 'Resep sayur asem / cara membuat sayur asem / Bagaimana cara membuat sayur asem?', 'Sayur asem Betawi adalah sup sayuran dengan kuah asam yang terbuat dari tamarind. Biasanya di dalamnya terdapat berbagai macam sayuran seperti kacang panjang, terong, labu siam, dan jagung.\r\n<br>\r\n<br>\r\nBahan Bahan:\r\n<br>\r\n•	200 gram kacang panjang, potong-potong\r\n<br>\r\n•	100 gram labu siam, potong-potong\r\n<br>\r\n•	100 gram terong, potong-potong\r\n<br>\r\n•	100 gram jagung manis, potong-potong\r\n<br>\r\n•	100 gram tahu putih, potong dadu\r\n<br>\r\n•	2 lembar daun salam\r\n<br>\r\n•	2 lembar daun jeruk\r\n<br>\r\n•	2 buah cabai merah, iris tipis\r\n<br>\r\n•	2 buah cabai hijau, iris tipis\r\n<br>\r\n•	1 batang serai, memarkan\r\n<br>\r\n•	1 liter air\r\n<br>\r\n•	2 sendok makan gula merah, serut\r\n<br>\r\n•	1 sendok teh asam jawa, larutkan dengan sedikit air\r\n<br>\r\n•	Garam secukupnya\r\n<br>\r\n<br>\r\nBumbu Halus:\r\n<br>\r\n•	5 butir bawang merah\r\n<br>\r\n•	3 siung bawang putih\r\n<br>\r\n•	3 buah kemiri, sangrai\r\n<br>\r\n•	1 sendok teh terasi bakar\r\n<br>\r\n<br>\r\nCara Membuat:\r\n<br>\r\n•	Rebus air dalam panci besar. Tambahkan daun salam, daun jeruk, serai, dan bumbu halus. Aduk rata.\r\n<br>\r\n•	Masukkan kacang panjang, labu siam, terong, jagung manis, dan tahu ke dalam panci. Masak hingga semua bahan matang.\r\n<br>\r\n•	Tambahkan cabai merah, cabai hijau, gula merah serut, dan garam. Aduk rata.\r\n<br>\r\n•	Terakhir, tambahkan larutan asam jawa sesuai dengan keasaman yang diinginkan. Aduk rata dan masak sebentar.\r\n<br>\r\n•	Cicipi sayur asem, tambahkan gula atau garam jika diperlukan.\r\n<br>\r\n•	Angkat sayur asem dari api dan sajikan selagi hangat.'),
(16, 'Resep asinan / cara membuat asinan / Bagaimana cara membuat asinan?', 'Asinan Betawi adalah campuran berbagai macam sayuran dan buah-buahan yang disiram dengan bumbu asam pedas. Biasanya terdapat timun, kol, wortel, nanas, dan bengkuang.\r\n<br>\r\n<br>\r\nBahan-Bahan:\r\n<br>\r\n•	250 gram kol, iris tipis\r\n<br>\r\n•	250 gram tauge, bersihkan\r\n<br>\r\n•	2 buah mentimun, iris tipis\r\n<br>\r\n•	2 buah wortel, iris tipis\r\n<br>\r\n•	2 buah kerupuk mie\r\n<br>\r\n•	2 sendok makan kacang tanah, sangrai dan haluskan\r\n<br>\r\n•	2 sendok makan bawang merah goreng\r\n<br>\r\n•	1 sendok makan gula merah, serut\r\n<br>\r\n•	1 sendok teh garam\r\n<br>\r\n•	Air secukupnya\r\n<br>\r\n•	Es batu secukupnya\r\n<br>\r\n<br>\r\nBahan Kuah Asinan:\r\n<br>\r\n•	500 ml air\r\n<br>\r\n•	200 gram gula merah, serut\r\n<br>\r\n•	150 ml cuka\r\n<br>\r\n•	2 sendok makan garam\r\n<br>\r\n•	1 sendok teh bubuk cabe\r\n<br>\r\n<br>\r\nCara membuat:\r\n<br>\r\n•	Campurkan semua bahan kuah asinan dalam panci dan masak hingga mendidih. Setelah itu, dinginkan.\r\n<br>\r\n•	Siapkan wadah atau mangkuk, letakkan kol, tauge, mentimun, dan wortel di atasnya.\r\n<br>\r\n•	Siramkan kuah asinan yang telah didinginkan ke atas sayuran hingga terendam.\r\n<br>\r\n•	Tambahkan kacang tanah halus, bawang merah goreng, gula merah serut, dan garam ke atas sayuran.\r\n<br>\r\n•	Sajikan Asinan Betawi dengan menambahkan kerupuk mie dan es batu di atasnya.\r\n'),
(17, 'Resep soto mie betawi / cara membuat soto mie betawi / Bagaimana cara membuat asinan?', 'Soto mie Betawi adalah soto dengan mie kuning, daging sapi, dan jeroan seperti usus, babat, dan babi panggang. Soto mie Betawi biasanya disajikan dengan tambahan koya (bubuk kerupuk) dan jeruk nipis.\r\n<br>\r\n<br>\r\nBahan-bahan:\r\n<br>\r\n•	200 gram mie kuning\r\n<br>\r\n•	200 gram daging sapi, iris tipis\r\n<br>\r\n•	2 lembar daun salam\r\n<br>\r\n•	2 batang serai, memarkan\r\n<br>\r\n•	2 cm lengkuas, memarkan\r\n<br>\r\n•	3 lembar daun jeruk\r\n<br>\r\n•	2 sendok makan minyak goreng\r\n<br>\r\n•	2 liter air\r\n<br>\r\n•	1 buah tomat, potong-potong\r\n<br>\r\n•	1 batang daun bawang, iris tipis\r\n<br>\r\n•	1 sendok teh garam\r\n<br>\r\n•	1 sendok teh gula\r\n<br>\r\n•	1 sendok teh merica bubuk\r\n<br>\r\n•	Bawang merah goreng untuk taburan\r\n<br>\r\n•	Seledri cincang untuk taburan\r\n<br>\r\n<br>\r\nBumbu Halus:\r\n<br>\r\n•	5 butir bawang merah\r\n<br>\r\n•	3 siung bawang putih\r\n<br>\r\n•	2 butir kemiri, sangrai\r\n<br>\r\n•	1 sendok teh ketumbar bubuk\r\n<br>\r\n•	1/2 sendok teh jintan bubuk\r\n<br>\r\n•	1/2 sendok teh bubuk kunyit\r\n<br>\r\n<br>\r\nCara membuat:\r\n<br>\r\n•	Rebus mie kuning hingga matang, tiriskan, dan sisihkan.\r\n<br>\r\n•	Panaskan minyak goreng dalam panci. Tumis bumbu halus, daun salam, serai, lengkuas, dan daun jeruk hingga harum.\r\n<br>\r\n•	Masukkan irisan daging sapi, aduk hingga berubah warna.\r\n<br>\r\n•	Tambahkan air, masak hingga mendidih dan daging menjadi empuk. Buang kotoran yang terapung di permukaan kaldu.\r\n<br>\r\n•	Setelah daging empuk, tambahkan tomat, daun bawang, garam, gula, dan merica bubuk. Aduk rata.\r\n<br>\r\n•	Siapkan mangkuk, tata mie kuning di dalamnya. Siram dengan kuah soto dan taburi dengan bawang merah goreng serta seledri cincang.\r\n<br>\r\n•	Soto Mie Betawi siap disajikan.\r\n'),
(18, 'Resep gado-gado / cara membuat gado-gado / Bagaimana cara membuat gado-gado?', 'Gado-gado Betawi adalah campuran sayuran segar seperti tauge, kacang panjang, kol, dan mentimun yang disiram dengan saus kacang. Biasanya disajikan dengan lontong atau ketupat.\r\n<br>\r\n<br>\r\nBahan-bahan:\r\n<br>\r\n•	200 gram tahu, potong dadu\r\n<br>\r\n•	200 gram tempe, potong dadu\r\n<br>\r\n•	200 gram kacang panjang, potong-potong\r\n<br>\r\n•	200 gram taoge\r\n<br>\r\n•	1 buah ketimun, iris tipis\r\n<br>\r\n•	1 buah mentimun, iris tipis\r\n<br>\r\n•	2 buah kentang, rebus dan potong-potong\r\n<br>\r\n•	2 lembar daun jeruk purut\r\n<br>\r\n•	2 lembar daun salam\r\n<br>\r\n•	2 sendok makan minyak goreng\r\n<br>\r\n•	1/2 sendok teh garam\r\n<br>\r\n•	1/2 sendok teh gula\r\n<br>\r\n•	1/2 sendok teh air asam jawa\r\n<br>\r\n•	Bawang merah goreng untuk taburan\r\n<br>\r\n<br>\r\nBumbu Kacang:\r\n<br>\r\n•	200 gram kacang tanah, sangrai\r\n<br>\r\n•	5 siung bawang putih, goreng\r\n<br>\r\n•	5 butir bawang merah, goreng\r\n<br>\r\n•	2 buah cabai merah keriting\r\n<br>\r\n•	2 sendok makan air asam jawa\r\n<br>\r\n•	1 sendok teh gula merah, serut\r\n<br>\r\n•	Garam secukupnya\r\n<br>\r\n<br>\r\nCara membuat:\r\n<br>\r\n•	Panaskan minyak goreng dalam wajan. Goreng tahu dan tempe hingga kecokelatan. Tiriskan.\r\n<br>\r\n•	Rebus kacang panjang dan taoge hingga matang. Tiriskan.\r\n<br>\r\n•	Panaskan minyak goreng dalam wajan, tumis daun jeruk dan daun salam hingga harum.\r\n<br>\r\n•	Masukkan bumbu kacang, aduk rata. Tambahkan air asam jawa, garam, gula, dan air secukupnya. Aduk hingga bumbu tercampur rata dan kuah kacang terbentuk.\r\n<br>\r\n•	Susun semua bahan (tahu, tempe, kacang panjang, taoge, ketimun, mentimun, dan kentang) di atas piring saji.\r\n<br>\r\n•	Siram dengan kuah kacang.\r\n<br>\r\n•	Taburi dengan bawang merah goreng.\r\n<br>\r\n•	Gado-gado Betawi siap disajikan.'),
(19, 'Resep semur betawi / cara membuat semur betawi / Bagaimana cara membuat semur betawi?', 'Semur Betawi adalah masakan daging sapi yang dimasak dengan bumbu rempah seperti bawang merah, bawang putih, ketumbar, dan kacang merah. Rasanya manis dan sedikit pedas.\r\n<br>\r\n<br>\r\nBahan-bahan:\r\n<br>\r\n•	500 gram daging sapi, potong-potong\r\n<br>\r\n•	3 sendok makan minyak goreng\r\n<br>\r\n•	2 lembar daun salam\r\n<br>\r\n•	2 batang serai, memarkan\r\n<br>\r\n•	2 cm lengkuas, memarkan\r\n<br>\r\n•	2 buah kapulaga\r\n<br>\r\n•	2 cm kayu manis\r\n<br>\r\n•	3 buah cengkeh\r\n<br>\r\n•	2 sendok makan kecap manis\r\n<br>\r\n•	1 sendok makan kecap asin\r\n<br>\r\n•	1 sendok makan gula merah, serut\r\n<br>\r\n•	500 ml air\r\n<br>\r\n•	Garam secukupnya\r\n<br>\r\n<br>\r\nBumbu Halus:\r\n<br>\r\n•	5 siung bawang putih\r\n<br>\r\n•	8 butir bawang merah\r\n<br>\r\n•	2 cm jahe\r\n<br>\r\n•	1/2 sendok teh merica bubuk\r\n<br>\r\n<br>\r\nCara membuat:\r\n<br>\r\n•	Panaskan minyak goreng dalam wajan. Tumis bumbu halus, daun salam, serai, lengkuas, kapulaga, kayu manis, dan cengkeh hingga harum.\r\n<br>\r\n•	Masukkan potongan daging sapi, aduk rata hingga daging berubah warna.\r\n<br>\r\n•	Tambahkan kecap manis, kecap asin, gula merah, garam, dan air. Aduk rata.\r\n<br>\r\n•	Masak semur dengan api kecil hingga daging empuk dan bumbu meresap, sekitar 1-2 jam. Tambahkan air jika diperlukan.\r\n<br>\r\n•	Koreksi rasa, tambahkan garam jika perlu.\r\n<br>\r\n•	Angkat dan sajikan Semur Betawi dengan nasi hangat.'),
(20, 'Resep rujak juhi betawi / cara membuat rujak juhi betawi / Bagaimana cara membuat rujak juhi betawi?', 'Rujak Juhi Betawi adalah campuran buah-buahan seperti mangga muda, nanas, dan kedondong yang disiram dengan saus bumbu kacang dan ditambahkan dengan irisan cumi kering.\r\n<br>\r\n<br>\r\nBahan-bahan:\r\n<br>\r\n•	200 gram juhi (cumicumi kering), rebus dan potong-potong\r\n<br>\r\n•	1 buah tahu putih, potong kotak kecil dan goreng\r\n<br>\r\n•	1 buah tempe, potong kotak kecil dan goreng\r\n<br>\r\n•	100 gram tauge, seduh dengan air panas\r\n<br>\r\n•	1 buah mentimun, potong-potong\r\n<br>\r\n•	1 buah mangga muda, potong-potong\r\n<br>\r\n•	1 buah kedondong, potong-potong\r\n<br>\r\n•	1 buah nanas, potong-potong\r\n<br>\r\n•	1 buah bengkoang, potong-potong\r\n<br>\r\n•	2 batang daun bawang, iris tipis\r\n<br>\r\n<br>\r\nBahan Bumbu Rujak:\r\n<br>\r\n•	10 buah cabai rawit merah, sesuai selera\r\n<br>\r\n•	5 buah cabai merah besar, buang biji\r\n<br>\r\n•	2 siung bawang putih\r\n<br>\r\n•	2 sendok makan gula merah\r\n<br>\r\n•	2 sendok makan kacang tanah goreng\r\n<br>\r\n•	1 sendok teh terasi bakar\r\n<br>\r\n•	Garam secukupnya\r\n<br>\r\n<br>\r\nCara membuat:\r\n<br>\r\n•	Haluskan semua bumbu rujak menggunakan blender atau ulekan.\r\n<br>\r\n•	Campurkan bumbu rujak dengan air secukupnya, aduk rata.\r\n<br>\r\n•	Siapkan piring saji, susun juhi, tahu, tempe, tauge, mentimun, mangga muda, kedondong, nanas, dan bengkoang di atas piring.\r\n<br>\r\n•	Siramkan bumbu rujak yang sudah dihaluskan ke atas bahan-bahan yang telah disusun.\r\n<br>\r\n•	Taburi dengan irisan daun bawang dan kacang tanah goreng.\r\n<br>\r\n•	Rujak Juhi Betawi siap disajikan.'),
(24, 'Resep Semur Jengkol khas Betawi/ Cara Membuat Semur Jengkol khas Betawi', '<p>Semur jengkol adalah makanan khas Betawi yang biasanya dijadikan lauk pendamping nasi uduk. Pada resep ini, jengkol diolah hingga lembut.</p>\r\n<p><strong>Bahan dan Bumbu</strong></p>\r\n<ul>\r\n<li>500 gram jengkol</li>\r\n<li>1 batang serai digeprek</li>\r\n<li>3 cm lengkuas digeprek</li>\r\n<li>2 lembar daun jeruk</li>\r\n<li>1 lembar daun salam</li>\r\n<li>3 butir cengkeh</li>\r\n<li>1/2 sdt pala bubuk</li>\r\n<li>1/2 sdt garam</li>\r\n<li>1/2 sdt lada bubuk (merica/sahang)</li>\r\n<li>1/2 sdt kaldu bubuk</li>\r\n<li>7 sdm kecap manis</li>\r\n<li>350 ml air untuk kuah</li>\r\n<li>Air secukupnya dan 16 lembar daun jambu biji/klutuk untuk rebusan jengkol secukupnya</li>\r\n<li>minyak untuk menumis bumbu</li>\r\n</ul>\r\n\r\n<p><strong>Haluskan</strong></p>\r\n<ul>\r\n<li>5 butir kemiri</li>\r\n<li>8 butir bawang merah</li>\r\n<li>3 siung bawang putih</li>\r\n<li>6 buah cabe merah besar</li>\r\n</ul>\r\n\r\n<p><strong>Cara Membuat Semur Jengkol khas Betawi</strong></p>\r\n<ol>\r\n<li>Kupas kulit jengkol dan cuci bersih, kemudian rebus dengan air secukupnya bersama 8 lembar daun jambu selama 60 menit. Buang daun jambu dan air rebusan pertama, ganti dengan air dan 8 lembar daun jambu yang baru lalu rebus kembali selama 60 menit hingga jengkol menjadi empuk.</li>\r\n<li>Angkat dan tiriskan jengkol, kemudian geprek-geprek namun tidak usah terlalu kuat hanya agar bumbu dapat meresap sempurna.</li>\r\n<li>Panaskan sedikit minyak dalam wajan, lalu tumis bumbu halus, daun jeruk, daun salam, cengkeh, lengkuas dan serai hingga harum. Masukkan air dan jengkolnya serta aduk rata, setelah mendidih beri garam, pala, lada, kaldu bubuk dan kecap manis, aduk rata.</li>\r\n<li>Masak hingga kuah mengental dan agak surut, jangan lupa aduk sesekali agar matang merata. Angkat dari wajan kemudian semur jengkol sudah siap untuk disajikan.</li>\r\n</ol>'),
(25, 'Resep Roti Buaya Khas Betawi/ Cara Membuat Roti Buaya Khas Betawi', '<p>Roti buaya merupakan roti khas masyarakat Betawi. Tak heran jika roti buaya selalu hadir pada setiap acara pernikahan yang digelar masyarakat Betawi sebagai salah satu seserahan. Makanan yang satu ini melambangkan simbol kesetiaan, dimana kita ketahui jika hewan buaya hanya kawin sekali seumur hidupnya.</p>\r\n<p><strong>Bahan Roti</strong></p>\r\n<ul>\r\n<li>700 gram tepung terigu protein tinggi</li>\r\n<li>275 ml air es</li>\r\n<li>50 gram susu bubuk</li>\r\n<li>20 gram ragi instan</li>\r\n<li>300 gram tepung terigu protein sedang</li>\r\n<li>10 gram soft alfaga</li>\r\n<li>5 butir kuning telur</li>\r\n<li>200 gram gula pasir</li>\r\n<li>150 ml susu cair</li>\r\n<li>2 putih telur</li>\r\n<li>75 gram margarine</li>\r\n<li>75 gram mentega</li>\r\n<li>50 gram buttersub milky</li>\r\n<li>15 gram garam</li>\r\n<li>10 gram bacom</li>\r\n</ul>\r\n<p><strong>Bahan Olesan</strong></p>\r\n<ul>\r\n<li>Susu evaporated secukupnya</li>\r\n<li>Mentega secukupnya</li>\r\n</ul>\r\n<p><strong>Langkah membuat roti buaya khas betawi</strong></p>\r\n<ol>\r\n<li>Masukkan untuk tepung terigu protein tinggi, tepung terigu protein sedang, susu bubuk, ragi instan, soft alfaga, kuning telur, air es, gula pasir, susu cair, dan putih telur. Campur semua bahan menjadi satu kemudian uleni hingga kalis.</li>\r\n<li>Masukkan untuk  margarine, garam, mentega, buttersub milky, dan bacom sambil terus diuleni sampai adonan menjadi kalis danjuga elastis. Bentuk menjadi bulat serta diamkan selama 30 menit sampai adonan mengembang berubah 2 kali lebih besar.</li>\r\n<li>Kempiskan adonan, lalu potong dan timbang adonan sesuai selera. Diamkan adonan kembali hingga 15 menit.</li>\r\n<li>Selanjutnya bisa menggulung atau roll adonan lalu bentuk adonan menyerupai hewan buaya.</li>\r\n<li>Oleskan loyang dengan margarine hingga merata, letakkan adonan roti buaya di atas loyang. Diamkan hingga kurang lebih 60 menit, setelah itu olesi menggunakan susu evaporated hingga merata.</li>\r\n<li>Selanjutnya bisa memasukkan loyang ke dalam oven dan panggang dengan suhu 190°C selama 30 menit sampai matang dan berwarna kuning kecoklatan. Angkat dan saat masih panas bisa mengolesi dengan mentega, hias sesuai selera.</li>\r\n<li>Sajikan roti buaya dan siap dinikmati.</li>\r\n</ol>'),
(26, 'Resep Kue Cucur Khas Betawi/ Cara Membuat Kue Cucur Khas Betawi', '<p>Kue cucur adalah jajanan tradisional khas Betawi yang berasal dari pulau Jawa. Makanan ini terbuat dari tepung beras dan gula jawa, bentuknya bulat dan agak tebal pada bagian tengah, tapi tipis di pinggirannya. Rasanya sendiri manis dan teksturnya lembut.</p>\r\n\r\n<p><strong>Bahan-bahan</strong></p>\r\n<ul>\r\n<li>75 gr/10 sdm tepung beras</li>\r\n<li>75 gr/10 sdm tepung terigu</li>\r\n<li>125 gr gula merah</li>\r\n<li>¼ sdt garam</li>\r\n<li>220 ml air</li>\r\n<li>Daun pandan</li>\r\n</ul>\r\n<p><strong>Langkah-langkah membuat</strong></p>\r\n<ol>\r\n<li>Siapkan panci dan masukkan gula merah, garam, air dan daun pandan. Masak hingga mendidih dan gula larut, lalu saring dan diamkan hingga dingin.</li>\r\n<li>Campurkan tepung beras, tepung terigu, dan air gula merah yang sudah dingin. Aduk hingga merata dan halus, pastikan tidak ada yang bergerindil. Lalu diamkan kurang lebih 30 menit.</li>\r\n<li>Panaskan minyak menggunakan api sedang cenderung kecil. Jangan menggunakan banyak minyak agar nanti kue cucur bersarang.</li>\r\n<li>Tuang satu sendok sayur adonan kue cucur ke dalam minyak panas. Tusuk bagian tengah agar matang merata.</li>\r\n<li>Jika sudah matang, angkat dan sajikan.</li>\r\n</ol>'),
(27, 'Resep Dodol Khas Betawi/ Cara Membuat Dodol Khas Betawi', '<p>Dodol Betawi ini banyak dijumpai saat menjelang hari raya ataupun hajatan. Dalam laman Okezone disebutkan bahwa dodol Betawi ini sarat akan makna, yaitu nilai kebersamaan, gotong royong, dan kekeluargaan. Maka tak heran, masyarakat Betawi menganggap bahwa pembuatan dodol dapat mempererat persaudaraan.</p>\r\n\r\n<p><strong>Bahan dodol Betawi</strong></p>\r\n<ul>\r\n<li>500 gr tepung ketan putih</li>\r\n<li>600 ml santan kental</li>\r\n<li>350 gr gula merah (boleh ditambahkan sesuai selera)</li>\r\n<li>350 gr gula pasir</li>\r\n<li>4 lembat daun pandan</li>\r\n</ul>\r\n<p><strong>Cara membuat dodol Betawi</strong></p>\r\n<ol>\r\n<li>Masak gula pasir, gula merah, santan, dan daun pandan. Aduk terus supaya santan tidak pecah. Tunggu sampai mendidih atau bisa pastikan gula larut lalu saring.</li>\r\n<li>Masukkan tepung beras dan tetap aduk secara merata dengan api kecil. Pastikan masak sampai dengan matang, mengental dan tidak lengket pada wajan. Umumnya proses sampai dengan lebih dari 5 jam.</li>\r\n<li>Setelah selesai, masukkan ke dalam wadah yang sudah disiapkan tunggu sampai dingin dan bisa langsung potong dan sajika.</li>\r\n</ol>'),
(28, 'Resep Kue Putu Mayang Khas Betawi/ Cara Membuat Kue Putu Mayang Khas Betawi', '<p>Kue putu mayang adalah salah satu kue tradisional khas Betawi. Bentuknya unik seperti mi dengan beraneka ragam warna.</p>\r\n<p><strong>Bahan I</strong></p>\r\n<ul>\r\n<li>150 gram tepung beras</li>\r\n<li>50 gram tepung tapioka</li>\r\n<li>1/2 sendok teh garam</li>\r\n<li>1/8 sendok teh vanili</li>\r\n</ul>\r\n<p><strong>Bahan II</strong></p>\r\n<ul>\r\n<li>300 ml santan dari 1/2 butir kelapa</li>\r\n<li>100 gram gula merah, sisir</li>\r\n<li>25 gram gula pasir</li>\r\n</ul>\r\n<p><strong>Pelengkap</strong></p>\r\n<ul>\r\n<li>100 gram kelapa agak muda, parut kasar</li>\r\n<li>1 lembar daun pandan</li>\r\n<li>1/4 sendok teh garam</li>\r\n</ul>\r\n<p><strong>Cara membuat putu mayang</strong></p>\r\n<ol>\r\n<li>Campur seluruh bahan II menjadi satu, kemudian masak hingga mendidih, saring.</li>\r\n<li>Setelah hangat, tuangkan ke dalamnya tepung beras, garam, serta vanili. Aduk hingga adonan tercampur rata.</li>\r\n<li>Kemudian masak dengan api kecil hingga adonan menggumpal. Tambahkan tepung tapioka, uleni adonan hingga rata.</li>\r\n<li>Masukkan ke dalam cetakan putu mayang, tekan memanjang di atas daun, gulung.</li>\r\n<li>Lalu kukus selama 10 menit hingga matang, dan hidangkan dengan pelengkap.</li>\r\n<li>Kue putu mayang siap disajikan. Sebagai alternatif kamu juga bisa mencampurkan aneka pewarna makanan ke dalam adonan untuk membuat kue putu mayang semakin cantik.</li>\r\n</ol>'),
(29, 'Resep Kue Rangi Khas Betawi/ Cara Membuat Kue Rangi Khas Betawi', '<p>Kue rangi berbahan dasar tepung sagu dan kelapa parut. Resep kue rangi dari Sajian Sedap ini dapat dibuat dengan cetakan kue rangi, snack maker, atau teflon.</p>\r\n<p><strong>Bahan Kue</strong></p>\r\n<ul>\r\n<li>200 gram kelapa tua, diparut kasar</li>\r\n<li>400 gram tepung sagu tani</li>\r\n<li>1 sendok teh garam</li>\r\n<li>125 ml air</li>\r\n</ul>\r\n<p><strong>Bahan Saus</strong></p>\r\n<ul>\r\n<li>150 gram gula merah</li>\r\n<li>200 ml air</li>\r\n<li>5 sendok teh tepung sagu tani, dilarutkan dengan lima sendok teh air</li>\r\n</ul>\r\n<p><strong>Cara membuat kue rangi</strong></p>\r\n<ol>\r\n<li>Campur tepung sagu tani, kelapa parut kasar, dan garam. Uleni sambil diaduk air sedikit-sedikit sampai teksturnya berbutir.</li>\r\n<li>Panasi snack maker dengan api kompor sedang. Tuang adonan dan tutupi snack maker. Masak selama lima menit sampai matang, angkat.</li>\r\n<li>Bikin sausnya, rebus air dan gula merah sampai larut kemudian saring. Jika terasa kurang kental, kentalkan dengan larutan tepung sagu. Aduk sampai mendidih.</li>\r\n<li>Santap kue rangi dengan sausnya.</li>\r\n</ol>'),
(30, 'Resep Kue Cente Manis Khas Betawi/ Cara Membuat Kue Cente Manis Khas Betawi', '<p>Cente manis atau cantik manis adalah kue tradisional khas Betawi yang terbuat dari hunkue atau tepung kacang hijau. Cara membuat cente manis cukup rebus semua bahannya.</p>\r\n<p><strong>Bahan</strong></p>\r\n<ul>\r\n<li>100 gram biji delima atau pacar cina</li>\r\n<li>750 ml santan</li>\r\n<li>1 lembar daun pandan, simpulkan</li>\r\n<li>14 sdt garam</li>\r\n<li>150 gram gula pasir</li>\r\n<li>75 gram tepung sari pati kacang hijau (hunkue)</li>\r\n<li>Daun pisang atau plastik mika secukupnya untuk bungkus</li>\r\n</ul>\r\n<p><strong>Cara membuat cente manis</strong></p>\r\n<ol>\r\n<li>Rebus biji delima dengan air secukupnya hingga bening dan matang. Angkat dan tiriskan. Siram air dingin.</li>\r\n<li>Ambil 100 mililiter santan, larutkan dengan tepung hunkue. Sisihkan.</li>\r\n<li>Rebus sisa santan bersama garam dan daun pandan hingga panas.</li>\r\n<li>Tuangkan larutan tepung hunkue sambil aduk hingga kental.</li>\r\n<li>Tambahkan biji delima, aduk hingga rata. Ambil daun pandan, pinggirkan.</li>\r\n<li>Ambil selembar daun pisang, isi dengan 1 sendok makan penuh adonan.</li>\r\n<li>Lipat hingga rapi. Biarkan hingga dingin dan mengeras. Sajikan kue cente manis.</li>\r\n</ol>'),
(31, 'Resep Kue Getuk Lindri Khas Betawi/ Cara Membuat Kue Getuk Lindri Khas Betawi', '<p>Getuk  Lindri termasuk jenis makanan khas Betawi yang berbahan dasar singkong. Singkong umumnya diolah dengan cara dikukus atau direbus. Lalu ditumbuk atau digiling, dan diberi tambahan gula serta pewarna makanan. Untuk penyajian, getuk lindri diberikan taburan parutan kelapa.</p>\r\n<p><strong>Bahan-bahan</strong></p>\r\n<ul>\r\n<li>1 kg singkong, lalu kupas</li>\r\n<li>200 gram gula pasir</li>\r\n<li>1/2 sendok teh vanili</li>\r\n<li>Pasta cokelat / pandan (bila dibutuhkan)</li>\r\n<li>100 ml air</li>\r\n<li>1/3 butir kelapa yang diparut kasar</li>\r\n<li>1/4 sendok teh garam</li>\r\n</ul>\r\n<p><strong>Cara membuat</strong></p>\r\n<ol>\r\n<li>Didihkan gula, air, dan vanili sampai kental. Kemudian angkat, dinginkan, dan sisihkan.</li>\r\n<li>Kukus singkong sampai matang dan lunak, lalu tumbuk selagi panas.</li>\r\n<li>Masukkan air rebusan gula tadi bersama pasta cokelat / pandan ke dalam singkong tumbuk, lalu aduk sampai halus dan tercampur rata.</li>\r\n<li>Giling adonan dengan alat hingga keluar bentuk mie, kemudian potong sesuai selera.</li>\r\n<li>Hidangkan bersama kelapa parut.</li>\r\n</ol>'),
(32, 'Resep Bubur Ase Khas Betawi/ Cara Membuat Bubur Ase Khas Betawi', '<p>Bubur ase merupakan kuliner Betawi yang kini sudah mulai langka. Sajian istimewa ini merupakan perpaduan antara bubur nasi yang disajikan bersama kuah ase dan asinan.</p>\r\n<p><strong>Bahan Bubur Ase Betawi</strong></p>\r\n<ul>\r\n<li>300 gr beras, rendam semalaman</li>\r\n<li>300 ml santan kental</li>\r\n<li>1 lt air</li>\r\n<li>2 lembar daun salam</li>\r\n<li>1/2 sdt garam</li>\r\n</ul>\r\n<p><strong>Semur daging</strong></p>\r\n<ul>\r\n<li>2 sdm minyak goreng</li>\r\n<li>5 butir bawang merah, haluskan</li>\r\n<li>4 siung bawang putih, haluskan</li>\r\n<li>3 butir kemiri, sangrai, haluskan</li>\r\n<li>3 cm lengkuas, memarkanCek Promo</li>\r\n<li>1/2 sdt garam</li>\r\n<li>1/2 sdt merica putih bubuk</li>\r\n<li>1/4 sdt ketumbar bubuk</li>\r\n<li>1/4 sdt pala bubuk</li>\r\n<li>400 gr daging sandung lamur, potong dadu 2 cm</li>\r\n<li>150 gr tempe, iris dadu kecil, goreng</li>\r\n<li>5 sdm kecap manis</li>\r\n<li>250 ml air</li>\r\n<p><strong>Asinan, campur rata</strong></p>\r\n<ul>\r\n<li>200 gr asinan sawi, iris 1 cm</li>\r\n<li>100 gr toge, siangi</li>\r\n<li>50 gr kol, iris memanjang</li>\r\n<li>4 buah cabai rawit, gerus kasar</li>\r\n<li>1 sdm cuka</li>\r\n<li>1/2 sdm gula</li>\r\n<li>1/2 sdt garam</li>\r\n<li>Pelengkap:</li>\r\n<li>Kacang tanah goreng</li>\r\n<li>Kerupuk merah</li>\r\n<li>Sambal</li>\r\n</ul>\r\n<p><strong>Cara membuat bubur ase Betawi</strong></p>\r\n<ol>\r\n<li>Bubur: Dalam panci, masukkan semua bahan. Rebus sambil diaduk hingga lembut. Angkat. Sisihkan</li>\r\n<li>Semur: Panaskan minyak dalam panci, tumis bawang merah, bawang putih, kemiri, dan lengkuas hingga harum</li>\r\n<li>Tambahkan garam, merica, ketumbar, dan pala bubuk. aduk rata</li>\r\n<li>Masukkan daging, tempe dan kecap, tumis sambil diaduk rata. Tuang air, didihkan. Masak hingga daging matang. Angkat, sisihkan</li>\r\n<li>Penyelesaian: Taruh bubur dalam mangkuk saji, tambahkan semur, dan asinan. Sajikan dengan pelengkap</li>\r\n</ol>'),
(33, 'Resep Kue Ape Khas Betawi/ Cara Membuat Kue Ape Khas Betawi', '<p>Kue ape atau dikenal dengan nama serabi Jakarta adalah makanan khas Betawi. Kue ini memiliki warna hijau dengan bentuk bulat pipih dengan bagian menonjol di tengahnya. Kue ape dibuat dengan campuran tepung, gula, telur dan bahan lainnya.</p>\r\n<p><strong>Bahan-bahan</strong></p>\r\n<ul>\r\n<li>100 gr tepung beras</li>\r\n<li>60 gr tepung terigu</li>\r\n<li>100 gr gula pasir</li>\r\n<li>1 butir telur</li>\r\n<li>1/4 sdt garam</li>\r\n<li>1/2 sdt baking powder</li>\r\n<li>1/4 sdt soda kue</li>\r\n<li>200 ml jus pandan</li>\r\n</ul>\r\n<p><strong>Cara Membuat</strong></p>\r\n<ol>\r\n<li>Campur semua bahan kering. Aduk rata.</li>\r\n<li>Masukkan telur, aduk dengan whisk sambil tuang jus pandan secara bertahap. Diamkan selama 1 jam.</li>\r\n<li>Panaskan wajan dengan api kecil.</li>\r\n<li>Olesi minyak dan tuang adonan, buat pinggiran tipis dan tebal di tengah.</li>\r\n<li>Tutup. Diamkan 1-2 menit. Angkat jika sudah kering.</li>\r\n<li>Sajikan.</li>\r\n</ol>'),
(34, 'Resep Selendang Mayang Khas Betawi/ Cara Membuat Selendang Mayang Khas Betawi', '<p>Selendang mayang adalah salah satu minuman tradisional Betawi . Sekarang mungkin sudah sulit sekali menemukan selendang mayang karena minuman ini dianggap minuman kuno. Kamu mungkin hanya bisa menemukannya di acara-acara tertentu, seperti Lebaran Betawi.</p>\r\n<p><strong>Bahan-bahan</strong></p>\r\n<ul>\r\n<li>100 gram tepung sagu tani</li>\r\n<li>100 gram tepung hunkwe</li>\r\n<li>1 liter air</li>\r\n</ul>\r\n<p><strong>Saus Gula</strong></p>\r\n<ul>\r\n<li>200 ml air<li>\r\n<li>200 gram gula merah<li>\r\n<li>1 lembar daun pandan<li>\r\n</ul>\r\n<p><strong>Kuah Santan</strong></p>\r\n<ul>\r\n<li>500 ml santan</li>\r\n<li>1 sdt garam</li>\r\n<li>1 lembar daun pandan</li>\r\n</ul>\r\n<p><strong>Tambahan</strong></p>\r\n<ul>\r\n<li>Pewarna makanan hijau secukupnya</li>\r\n<li>Pewarna makanan merah secukupnya</li>\r\n<li>Es batu secukupnya</li>\r\n</ul>\r\n<p><strong>Cara Membuat</strong></p>\r\n<ol>\r\n<li>Pertama-tama, siapkan loyang kemudian alasi permukaannya dengan plastik. Sisihkan.</li>\r\n<li>Ambil wadah, kemudian campur bahan selendang mayang dan aduk sampai merata. Bagi adonan menjadi 3 bagian lalu beri satu bagian pewarna hijau, beri satu bagian pewarna merah, dan biarkan satu bagiannya tetap berwarna putih.</li>\r\n<li>Masak adonan warna merah dengan api kecil sambil terus diaduk hingga meletup-letup dan adonan terlihat jadi bening kemudian tuangkan ke dalam loyang. Sisihkan.</li>\r\n<li>Masak adonan warna putih dengan api kecil sambil terus diaduk hingga meletup-letup dan adonan terlihat jadi bening. Tuang ke dalam loyang di atas adonan merah. Sisihkan.</li>\r\n<li>Masak adonan warna hijau dengan api kecil sambil terus diaduk hingga meletup-letup dan adonan terlihat jadi bening. Tuang ke dalam loyang di atas adonan putih. Sisihkan dan biarkan mengeras.</li>\r\n<li>Dalam panci, campur semua bahan saus gula. Masak hingga mendidih dan gula larut. Angkat dan sisihkan.</li>\r\n<li>Siapkan panci yang berbeda, kemudian campurkan semua bahan kuah santan. Masak hingga mendidih sambil terus diaduk-aduk. Angkat dan sisihkan.</li>\r\n<li>Keluarkan selendang mayang dari loyang dan potong-potong kotak sesuai selera.</li>\r\n<li>Tata selendang mayang dalam gelas saji. Tuang kuah santan dan saus gula. Beri es batu. Siap disajikan untuk seluruh anggota keluarga.</li>\r\n</ol>');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_user`
--

CREATE TABLE `tbl_user` (
  `id_user` int(11) NOT NULL,
  `nama` varchar(250) NOT NULL,
  `username` varchar(250) NOT NULL,
  `password` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tbl_user`
--

INSERT INTO `tbl_user` (`id_user`, `nama`, `username`, `password`) VALUES
(1, 'farhan kamil', 'admin', '$2y$10$mXByqqJr.7vcjE4qemm1pOWNzrnQVtpKWrmrjcB8hspEzqvqDBI5u'),
(2, 'anu', 'anuan', '$2y$10$6PG8tkeMZ6tJ1Dego/EaqOVFpuykxhZZ6CQdGdKCFbmufbB3mTf8y'),
(3, 'gift coklat', '12345', '$2y$10$DZ9W5Cllgk0UbxHjlYphAOgco8F.l.q9uOqkSSo9GFi18vbzBhNp.'),
(4, 'obi', 'obi', '$2y$10$KWJucq9aHQ66SuwQdMAi9uT7wR9Y5S.XVg2gzZatdHjFkqFvUt2im');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `chat`
--
ALTER TABLE `chat`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_user`
--
ALTER TABLE `tbl_user`
  ADD PRIMARY KEY (`id_user`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `chat`
--
ALTER TABLE `chat`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;

--
-- AUTO_INCREMENT for table `tbl_user`
--
ALTER TABLE `tbl_user`
  MODIFY `id_user` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
